resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/finalight/rnsample.git
    branch: master


# - name: node-image
#   type: registry-image
#   source:
#     repository: node

- name: android-emulator-image
  type: registry-image
  source:
    repository: finalight/detox-android-emulator

jobs:
# - name: unit-test
#   public: true
#   plan:
#   - get: node-image
#   - get: repo
#     trigger: true
#   - task: install
#     image: node-image
#     config:
#       inputs:
#       - name: repo
#       outputs:
#       - name: dependencies
#         path: repo/node_modules
#       platform: linux
#       run:
#         path: npm
#         args: ["install"]
#         dir: repo
#   - task: test
#     image: node-image
#     config:
#       inputs:
#       - name: repo
#       - name: dependencies
#         path: repo/node_modules
#       platform: linux
#       run:
#         path: npm
#         args: ["run", "test"]
#         dir: repo
- name: e2e-test
  public: true
  plan:
  - get: android-emulator-image
  - get: repo
    trigger: true
    # passed: [unit-test]
  - task: install
    image: android-emulator-image
    config:
      inputs:
      - name: repo
      outputs:
      - name: dependencies
        path: repo/node_modules
      platform: linux
      run:
        user: root
        path: sh
        args:
        - -xc
        - |
          npx detox build -c android
          npx detox test -c android --headless
        dir: repo