resources:
- name: repo
  type: git
  icon: github
  source:
    uri: git@github.com:pivotal-sg/healthy-heads.git
    branch: master
    private_key: ((secrets.privatekey))

# - name: node-image
#   type: registry-image
#   source:
#     repository: node

# - name: fastlane-image
#   type: registry-image
#   source:
#     repository: finalight/fastlane

- name: android-emulator-image
  type: registry-image
  source:
    repository: finalight/android

jobs:
# - name: unit-test
#   public: true
#   plan:
#   - get: node-image
#   - get: repo
#     trigger: true
#   - task: install
#     image: node-image
#     config:
#       inputs:
#       - name: repo
#       outputs:
#       - name: dependencies
#         path: repo/node_modules
#       platform: linux
#       run:
#         path: npm
#         args: ["install"]
#         dir: repo
#   - task: test
#     image: node-image
#     config:
#       inputs:
#       - name: repo
#       - name: dependencies
#         path: repo/node_modules
#       platform: linux
#       run:
#         path: npm
#         args: ["run", "test"]
#         dir: repo
- name: e2e-test
  public: true
  plan:
  - get: android-emulator-image
  - get: repo
    trigger: true
    # passed: [unit-test]
  - task: install
    image: android-emulator-image
    config:
      inputs:
      - name: repo
      # outputs:
      # - name: dependencies
      #   path: /home/node_modules
      platform: linux
      run:
        user: root
        path: sh
        args:
        - -xc
        - |
          npm i
          echo ((secrets.key)) > keystore.b64 
          base64 -d keystore.b64 > ./android/app/my-upload-key.keystore
          npm run e2e:android
        dir: repo
# - name: deploy-android
#   public: true
#   plan:
#   - get: fastlane-image
#   - get: repo
#     trigger: true
#     # passed: [unit-test]
#   - task: deploy
#     image: fastlane-image
#     config:
#       caches:
#       - path: node-modules/
#       inputs:
#       - name: repo
#       platform: linux
#       run:
#         user: root
#         path: sh
#         args: 
#         - -xc
#         - |
#           echo ((rnsamplekeystore.googleserviceaccount)) > googleserviceaccount.b64 
#           base64 -d googleserviceaccount.b64 > google-service-account.json
#           echo ((rnsamplekeystore.key)) > keystore.b64 
#           base64 -d keystore.b64 > ./app/my-upload-key.keystore
#           cd ../
#           npm i
#           cd android
#           fastlane android deploy_internal
#         dir: repo/android
